<?php
namespace WHCM\Core;

use WHCM\Core\SecretStore;

class EmailTemplate {
    private static function getSmtpConfig(): array {
        $db=Bootstrap::getDB();$keys=['smtp_enabled','smtp_host','smtp_port','smtp_username','smtp_password','smtp_encryption','smtp_from_address','smtp_from_name'];$settings=[];
        foreach($keys as $key){$stmt=$db->prepare('SELECT key_value FROM settings WHERE tenant_id=0 AND key_name=? LIMIT 1');$stmt->execute([$key]);$row=$stmt->fetch();$settings[$key]=$row!==false?$row['key_value']:'';if($key==='smtp_password'&&$settings[$key]!=='')$settings[$key]=SecretStore::decrypt((string)$settings[$key]);}
        if(!empty($settings['smtp_host']))return ['enabled'=>($settings['smtp_enabled']??'')==='1','host'=>$settings['smtp_host'],'port'=>(int)($settings['smtp_port']?:587),'username'=>$settings['smtp_username'],'password'=>$settings['smtp_password'],'encryption'=>$settings['smtp_encryption']?:'tls','from_address'=>$settings['smtp_from_address']?:'noreply@localhost','from_name'=>$settings['smtp_from_name']?:Bootstrap::getConfig('app.name','پُست‌یار')];
        return Bootstrap::getConfig('mail',[]);
    }
    private static function sendWithDbConfig(string $to,string $subject,string $body): bool {
        $config=self::getSmtpConfig();$from=$config['from_address']??'noreply@localhost';$fromName=$config['from_name']??Bootstrap::getConfig('app.name','پُست‌یار');$hasSmtp=!empty($config['host'])&&(($config['auth']??'1')!=='1'||!empty($config['username']));
        if($hasSmtp&&class_exists('\\PHPMailer\\PHPMailer\\PHPMailer')){try{$mail=new \PHPMailer\PHPMailer\PHPMailer(true);$mail->isSMTP();$mail->Host=$config['host'];$mail->Port=(int)($config['port']??587);$mail->SMTPAuth=(($config['auth']??'1')==='1');$mail->Username=$config['username'];$mail->Password=$config['password']??'';$mail->SMTPSecure=$config['encryption']??'tls';$mail->CharSet='UTF-8';$mail->setFrom($from,$fromName);$mail->addAddress($to);$mail->Subject=$subject;$mail->Body=$body;$mail->isHTML(true);return $mail->send();}catch(\Exception $e){error_log('[Postyar EmailTemplate] SMTP Error: '.$e->getMessage());}}
        $headers="From: ".$fromName." <".$from.">\r\n"; $headers.="Reply-To: ".$from."\r\n";$headers.="MIME-Version: 1.0\r\n";$headers.="Content-Type: text/html; charset=UTF-8\r\n";$headers.="X-Mailer: Postyar-EmailTemplate/1.0\r\n";return \mail($to,'=?UTF-8?B?'.base64_encode($subject).'?=',$body,$headers);
    }
    public static function sendByEvent(string $eventKey,int $userId,array $variables=[]): bool {
        $template=self::getTemplate($eventKey);if(!$template||!($template['is_active']??1))return false;$db=Bootstrap::getDB();$stmt=$db->prepare('SELECT email,name FROM users WHERE id=? LIMIT 1');$stmt->execute([$userId]);$user=$stmt->fetch();if(!$user)return false;$to=$user['email'];$variables['app_name']=Bootstrap::getConfig('app.name','پُست‌یار');$variables['app_url']=Bootstrap::getConfig('app.url','');if(empty($variables['name']))$variables['name']=$user['name']??'';$subject=self::renderTemplate($template['subject'],$variables);$body=self::renderTemplate($template['body_html'],$variables);$status='sent';$error=null;try{if(!self::sendWithDbConfig($to,$subject,$body)){$status='failed';$error='خطا در ارسال ایمیل.';}}catch(\Throwable $e){$status='failed';$error='خطای ارسال ایمیل.';error_log('[Postyar EmailTemplate] sendByEvent: '.$e->getMessage());}try{$stmt=$db->prepare('INSERT INTO email_log(template_id,to_address,user_id,subject,status,error_message) VALUES(?,?,?,?,?,?)');$stmt->execute([$template['id'],$to,$userId,$subject,$status,$error]);}catch(\Exception $e){}return $status==='sent';
    }
    public static function testConnection(int $userId): array {$template=self::getTemplate('welcome');if(!$template||!($template['is_active']??1))return['success'=>false,'error'=>'قالب خوش‌آمدگویی فعال پیدا نشد.'];$db=Bootstrap::getDB();$stmt=$db->prepare('SELECT email,name FROM users WHERE id=? LIMIT 1');$stmt->execute([$userId]);$user=$stmt->fetch();if(!$user||empty($user['email']))return['success'=>false,'error'=>'نشانی ایمیل مدیر پیدا نشد.'];$vars=['name'=>$user['name']??'مدیر سیستم','app_name'=>Bootstrap::getConfig('app.name','پُست‌یار'),'app_url'=>Bootstrap::getConfig('app.url','')];$subject=self::renderTemplate($template['subject'],$vars);$body=self::renderTemplate($template['body_html'],$vars);try{$sent=self::sendWithDbConfig($user['email'],$subject,$body);return $sent?['success'=>true,'error'=>null]:['success'=>false,'error'=>'سرور ایمیل پیام را نپذیرفت.'];}catch(\Throwable $e){return['success'=>false,'error'=>$e->getMessage()?:'خطای ناشناخته در ارتباط با سرور ایمیل.'];}}
    public static function sendBulk(string $eventKey,array $userIds,array $variablesPerUser=[]): array {$r=['sent'=>0,'failed'=>0,'errors'=>[]];foreach($userIds as $uid){$uid=(int)$uid;$ok=self::sendByEvent($eventKey,$uid,$variablesPerUser[$uid]??[]);if($ok)$r['sent']++;else{$r['failed']++;$r['errors'][]='کاربر #'.$uid;}}return $r;}
    public static function renderTemplate(string $html,array $variables): string {foreach($variables as $key=>$value)$html=str_replace('{{'.$key.'}}',(string)$value,$html);return $html;}
    public static function getTemplate(string $eventKey): ?array {$db=Bootstrap::getDB();$stmt=$db->prepare('SELECT * FROM email_templates WHERE event_key=? LIMIT 1');$stmt->execute([$eventKey]);$row=$stmt->fetch();return $row?:null;}
    public static function getAllTemplates(): array {$db=Bootstrap::getDB();return $db->query('SELECT * FROM email_templates ORDER BY id ASC')->fetchAll();}
    public static function saveTemplate(string $eventKey,string $name,string $subject,string $bodyHtml,array $variables,bool $active): void {$db=Bootstrap::getDB();$vars=json_encode($variables,JSON_UNESCAPED_UNICODE);$stmt=$db->prepare('SELECT id FROM email_templates WHERE event_key=? LIMIT 1');$stmt->execute([$eventKey]);$existing=$stmt->fetch();if($existing){$stmt=$db->prepare('UPDATE email_templates SET template_name=?,subject=?,body_html=?,variables=?,is_active=? WHERE id=?');$stmt->execute([$name,$subject,$bodyHtml,$vars,$active?1:0,$existing['id']]);}else{$stmt=$db->prepare('INSERT INTO email_templates(event_key,template_name,subject,body_html,variables,is_active) VALUES(?,?,?,?,?,?)');$stmt->execute([$eventKey,$name,$subject,$bodyHtml,$vars,$active?1:0]);}}
    public static function deleteTemplate(int $id): void {$db=Bootstrap::getDB();$stmt=$db->prepare('DELETE FROM email_templates WHERE id=?');$stmt->execute([$id]);}
    public static function getLog(int $limit=50,int $offset=0,?string $statusFilter=null): array {$db=Bootstrap::getDB();$sql='SELECT el.*,u.name user_name FROM email_log el LEFT JOIN users u ON el.user_id=u.id WHERE 1=1';$params=[];if($statusFilter!==null&&in_array($statusFilter,['sent','failed'],true)){$sql.=' AND el.status=?';$params[]=$statusFilter;}$sql.=' ORDER BY el.id DESC LIMIT ? OFFSET ?';$params[]=$limit;$params[]=$offset;$stmt=$db->prepare($sql);$stmt->execute($params);return $stmt->fetchAll();}
    public static function getAdminEmailStats(): array {$db=Bootstrap::getDB();$sent=0;$failed=0;try{$sent=(int)$db->query("SELECT COUNT(*) FROM email_log WHERE status='sent'")->fetchColumn();}catch(\Exception $e){}try{$failed=(int)$db->query("SELECT COUNT(*) FROM email_log WHERE status='failed'")->fetchColumn();}catch(\Exception $e){}$by=[];try{$rows=$db->query("SELECT et.event_key,et.template_name,SUM(CASE WHEN el.status='sent' THEN 1 ELSE 0 END) sent_count,SUM(CASE WHEN el.status='failed' THEN 1 ELSE 0 END) failed_count FROM email_log el LEFT JOIN email_templates et ON el.template_id=et.id GROUP BY el.template_id ORDER BY sent_count DESC")->fetchAll();foreach($rows as $row)$by[]=$row;}catch(\Exception $e){}return['total_sent'=>$sent,'total_success'=>$sent,'total_attempts'=>$sent+$failed,'total_failed'=>$failed,'by_template'=>$by];}
}
